### ISSUE TITLE
Data loading error when log sequence length is longer than max length of bert tokenizer

### ISSUE THREAD

**Issue by ChangNamAn** [LogIntelligence/NeuralLog#1]
Hi,

I got the error message as below.
"Token indices sequence length is longer than the specified maximum sequence length for this model (651 > 512)"

It is fixed to set max_length=512 on data_loader.py.
inputs = bert_tokenizer(s, return_tensors='tf'**, max_length=512**)

**Comment by vanhoanglepsa** [comment]
Hi. Thanks for pointing it out!
We've updated our code!
https://github.com/vanhoanglepsa/NeuralLog/blob/93b81d3540479d0667d528abea0a5415b4107c16/neurallog/data_loader.py#L46
