### ISSUE TITLE
[QST]Question about the functioning of the Neural

### ISSUE THREAD

**Issue by Levi-zz** [LogIntelligence/NeuralLog#2]
Good afternoon, a question. Are neural-train.pkl and neural-test.pkl the trained models for HDFS and BGL?
If I wanted to test NeuralLog for apaches in [loghub](https://github.com/logpai/loghub/blob/master/Apache/Apache_2k.log) could I keep both, but adapting the inputs?

**Comment by vanhoanglepsa** [comment]
Hi @Levi-zz ,

_neural-train.pkl_ and _neural-test.pkl_ are just data files generated by **data_loader.py**. 
https://github.com/vanhoanglepsa/NeuralLog/blob/d5917e319b928a64408f7cafc43c2ac6fecf12e7/neurallog/data_loader.py#L422-L429

If you want to test on other datasets, you need to add a preprocessing step to generate training & testing data using fixed/sliding/session windows. In our code, we have these functions for the HDFS dataset:
https://github.com/vanhoanglepsa/NeuralLog/blob/d5917e319b928a64408f7cafc43c2ac6fecf12e7/neurallog/data_loader.py#L127-L131
or for BGL, Thunderbird, and Spirit datasets (Supercomputer-based datasets):
https://github.com/vanhoanglepsa/NeuralLog/blob/d5917e319b928a64408f7cafc43c2ac6fecf12e7/neurallog/data_loader.py#L300-L301

You can also refer to this demo about data preprocessing and training phases:
https://github.com/vanhoanglepsa/NeuralLog/blob/d5917e319b928a64408f7cafc43c2ac6fecf12e7/demo/NeuralLog.py#L116-L127

**Comment by Levi-zz** [comment]
Thank you very much for the feedback.
I reading your article saw that the window_size was 20, but I still don't understand the types of window(fixed/sliding/session).
What would be the difference and why for HDFS could only the session?
Sorry to bother you. It's because I intend to test NeuralLog and LogBert in my master's thesis.
If you prefer and it's not a problem I can contact your email: vanhoang.le@uon.edu.au.

THANKS

**Comment by vanhoanglepsa** [comment]
For the HDFS dataset, it only has the label for sessions, thus, we can only use the session window for evaluation.
You can email me and I will explain in more detail.
